build:
  maxIssues: 0

config:
  validation: true

complexity:
  LongMethod:
    active: true
    threshold: 200
  CyclomaticComplexMethod:
    active: true
    threshold: 22
  TooManyFunctions:
    active: true
    thresholdInFiles: 40
    thresholdInClasses: 40
    thresholdInInterfaces: 20
    thresholdInObjects: 25
    thresholdInEnums: 15
  LongParameterList:
    active: true
    functionThreshold: 14
    constructorThreshold: 10
  LargeClass:
    active: false

potential-bugs:
  UnsafeCallOnNullableType:
    active: true

style:
  MaxLineLength:
    active: true
    maxLineLength: 180
  WildcardImport:
    active: true
  UnusedImports:
    active: true
  MagicNumber:
    active: false

naming:
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
